### ISSUE TITLE
About the parameters setting of colmap2mvsnet.py

### ISSUE THREAD

**Issue by sy8008** [jshmsjh/3d-building-reconstruction#1]
Hello!
I am also trying to use AA-RMVSNet together with colmap on custom dataset. But always fail to get such a good point cloud. I guess it is the issue of depth related parameters setting. I wonder why did you set the depth_interval to 1.06 and max_d to 512 on colmap2mvsnet.py, and what it is the relationship between the parameters of colmap2mvsnet.py and that of AA-RMVSNet? Should the setting of depth_interval and max_d(number_of_depth) be the same on both AA-RMVSNet and colmap2mvsnet.py?
Thank you!

**Comment by jshmsjh** [comment]
Hi!
Sorry for the late response. The hyperparameters do influence the result, and we did several rounds of tests to finally get a visually good result. To the best of my knowledge, the depth_interval and max_d in AA_RMVSNet and colmap2mvsnet.py seem to be independent.

Please note that the quality of your dataset is also very important. In our tests, we find that the resolution of the pictures matters, and the photos taken at noon work better than that taken at dawn.

**Comment by sy8008** [comment]
Thank you for your reply!
